import { enquiryEn, enquiryListEn } from "./en-admin-enquiries";

export const adminEn = {
  meta: {
    title: "Sales admin | Aurora Residence",
    loginTitle: "Sign in | Aurora Residence admin",
    residenceTitle: "Residence {number} | Sales admin",
    enquiriesTitle: "Enquiries | Sales admin",
    enquiryTitle: "Enquiry | Sales admin",
  },
  common: {
    salesAdmin: "Sales admin",
    home: "Aurora Residence admin, dashboard",
    checkingSession: "Checking your session",
    footer: "© 2026 Meridian Group. Fictional project for portfolio.",
  },
  login: {
    title: "Sign in",
    lead: "For Aurora Residence sales managers.",
    email: "Email",
    password: "Password",
    submit: "Sign in",
    submitting: "Signing in",
    forgot: "Forgot password? Ask the site administrator.",
    emailInvalid: "Enter a valid email address",
    passwordRequired: "Enter your password",
    wrongCredentials: "Wrong email or password. {count} {attempts} left, then sign-in pauses for 15 minutes.",
    attemptOne: "attempt",
    attemptMany: "attempts",
    paused: "Too many failed attempts. Sign-in is paused, try again in {count} {minutes}.",
    minuteOne: "minute",
    minuteMany: "minutes",
    failed: "Could not reach the server. Check the connection and try again.",
  },
  nav: {
    label: "Admin sections",
    dashboard: "Dashboard",
    residences: "Residences",
    enquiries: "Enquiries",
    logout: "Log out",
    loggingOut: "Logging out",
  },
  roles: {
    ADMIN: "Administrator",
    MANAGER: "Sales manager",
  },
  placeholder: {
    title: "Coming in task 6c",
    text: "The enquiries screen is not built yet. New enquiries are already counted on the dashboard, and reservations will be made from an enquiry here.",
    back: "Back to dashboard",
  },
  states: {
    loadFailed: "Could not load the data. Check the connection and try again.",
    retry: "Try again",
    loading: "Loading",
  },
  dashboard: {
    title: "Dashboard",
    subtitle: "{date}. Aurora Residence, {total} residences.",
    statsLabel: "Residence and enquiry totals",
    available: "Available",
    reserved: "Reserved",
    sold: "Sold",
    newToday: "New enquiries today",
    ofTotal: "of {total} residences",
    endingSoonOne: "1 reservation ends within 2 days",
    endingSoonMany: "{count} reservations end within 2 days",
    noneEndingSoon: "None end within 2 days",
    shareOfHouse: "{percent}% of the house",
    waitingForCall: "{count} still waiting for a call",
    shareLabel: "Available {available}, reserved {reserved}, sold {sold}",
  },
  facade: {
    title: "Facade",
    lead: "Live status of every residence",
    entrance: "Entrance",
    floor: "Floor {floor}",
    residence: "Residence {number}, {status}",
    legend: "{status} {count}",
    statuses: { AVAILABLE: "Available", RESERVED: "Reserved", SOLD: "Sold" },
  },
  reservations: {
    title: "Reservations ending soon",
    lead: "Each reservation lasts 7 days. Extend or release before it ends.",
    all: "All reserved",
    empty: "No active reservations right now.",
    ends: "Ends {date}",
    endsToday: "Ends today",
    dayOne: "1 day left",
    dayMany: "{count} days left",
    noClient: "No enquiry",
  },
  residences: {
    title: "Residences",
    lead: "{total} residences on {floors} floors. Changes go live on the site the moment you save.",
    totals: "House totals",
    totalAvailable: "{count} available",
    totalReserved: "{count} reserved",
    totalSold: "{count} sold",
    searchLabel: "Search by residence number",
    searchPlaceholder: "Search by number, e.g. 7.03",
    floorLabel: "Floor",
    allFloors: "All floors",
    floorOption: "Floor {floor}",
    statusFilter: "Filter by status",
    all: "All",
    showing: "Showing {shown} of {total}",
    tableLabel: "Residences, {shown} shown",
    columns: {
      residence: "Residence",
      floor: "Floor",
      bedrooms: "Bedrooms",
      area: "Area, m²",
      price: "Price, USD",
      status: "Status",
      updated: "Updated",
      action: "Action",
    },
    studio: "Studio",
    penthouse: "Penthouse, incl. terrace",
    brief: "{bedrooms}, {area} m²",
    bedroomsShort: "{count} bd",
    open: "Open",
    openLabel: "Open residence {number}",
    empty: "No residences match these filters.",
    reset: "Reset filters",
  },
  residence: {
    back: "All residences",
    title: "Residence {number}",
    summary: "Floor {floor} of {floors}",
    bedroomsOne: "1 bedroom",
    bedroomsMany: "{count} bedrooms",
    studio: "Studio",
    area: "{area} m²",
    penthouse: "Penthouse, incl. terrace",
    viewOnSite: "View on site",
    viewOnSiteLabel: "View residence {number} on the site, opens in a new tab",
    planLabel: "Plan of residence {number}",
    specs: {
      floor: "Floor",
      floorValue: "{floor} of {floors}",
      bedrooms: "Bedrooms",
      area: "Area",
      layout: "Layout",
      ceiling: "Ceiling height",
      ceilingValue: "{height} m",
      view: "View",
    },
    places: {
      1: "north, by the core on the left",
      2: "north, by the core on the right",
      3: "south, left of centre",
      4: "south, right of centre",
      5: "west end, dual aspect",
      6: "east end, dual aspect",
    } as Record<number, string>,
    sides: { NORTH: "North", SOUTH: "South", WEST: "West", EAST: "East" } as Record<string, string>,
    priceStatus: {
      title: "Price and status",
      lead: "Saved changes reach the site at once.",
      price: "Price, USD",
      priceInvalid: "Enter whole dollars from $10 000 to $10 000 000.",
      status: "Status",
      statusLabel: "Status of residence {number}",
      reservedOnlyFromEnquiry: "Reserved is set from an enquiry",
      save: "Save changes",
      saving: "Saving",
      cancel: "Cancel",
      unchanged: "Nothing to save yet: change the price or the status.",
      saved: "Saved. The site shows the new values.",
    },
    confirm: {
      title: "Save changes to {number}?",
      price: "Price {from} → {to}",
      status: "Status {from} → {to}",
      releaseNote: "The active reservation ends now.",
      soldNote: "The active reservation closes as a sale.",
      note: "Note for the history (optional)",
      notePlaceholder: "For example, Autumn price list",
      confirm: "Confirm",
      cancel: "Cancel",
    },
    reservation: {
      title: "Reservation",
      lead: "Reserve after a call, when the client has decided. The residence returns to Available by itself when the reservation ends.",
      none: "No active reservation.",
      soldNote: "Sold residences cannot be reserved.",
      client: "Linked enquiry",
      noEnquiry: "No enquiry",
      ends: "Reservation ends",
      reservedBy: "Reserved by {author} on {date}",
      release: "Release reservation",
      releasing: "Releasing",
      releaseTitle: "Release the reservation of {number}?",
      releaseText: "{client} loses the hold now. The residence becomes Available on the site at once.",
      releaseConfirm: "Release",
      released: "Reservation released. The residence is Available again.",
      enquiryLabel: "Linked enquiry",
      enquiryOption: "{name}, {received}",
      endsHint: "7 days from the moment you reserve",
      reserve: "Reserve for 7 days",
      reserving: "Reserving",
      reserveNote: "The facade, floor plan and list on the site switch to Reserved at once.",
      noOpenEnquiries: "No open enquiries for {number}. A reservation is made for an enquiry about this residence: link it to a general enquiry first.",
      reserveTitle: "Reserve {number} for {client}?",
      reserveText: "The residence becomes Reserved on the site at once. The reservation ends on {date} unless you release it or sell the residence.",
      reserveStatus: "The enquiry moves from New to In progress.",
    },
    enquiries: {
      title: "Enquiries for {number}",
      empty: "No enquiries for this residence yet.",
      failed: "Could not load the enquiries.",
      openLabel: "Open enquiry from {name}",
    },
    history: {
      title: "Status and price history",
      empty: "No changes yet.",
      failed: "Could not load the history.",
      label: "{from} to {to}",
    },
    errors: {
      conflict: "Someone changed this residence a moment ago. The card now shows the current state; check it and try again.",
      rejected: "The change was not accepted. Check the values and try again.",
      failed: "Could not save. Check the connection and try again.",
    },
    notFound: {
      title: "Residence not found",
      text: "There is no such residence in the house. Numbers go from 1.01 to 11.06.",
    },
  },
  enquiries: {
    title: "Latest enquiries",
    lead: "{shown} of {total}. Enquiries never reserve a residence by themselves.",
    all: "All enquiries",
    empty: "No enquiries yet. New ones appear here as soon as they arrive.",
    today: "Today, {time}",
    yesterday: "Yesterday, {time}",
    residence: "Residence {number}",
    general: "General",
    studio: "Studio",
    bedrooms: "{count} bd",
    details: "{bedrooms}, {area} m², {price}",
    open: "Open",
    openLabel: "Open enquiry from {name}",
    statuses: { NEW: "New", IN_PROGRESS: "In progress", CLOSED: "Closed" },
    columns: {
      received: "Received",
      client: "Client",
      phone: "Phone",
      residence: "Residence",
      status: "Status",
      action: "Action",
    },
  },
  enquiryList: enquiryListEn,
  enquiry: enquiryEn,
};

export type AdminDictionary = typeof adminEn;

export function getAdminDictionary(): AdminDictionary {
  return adminEn;
}
