export const adminEn = {
  meta: {
    title: "Sales admin | Aurora Residence",
    loginTitle: "Sign in | Aurora Residence admin",
  },
  common: {
    salesAdmin: "Sales admin",
    home: "Aurora Residence admin, dashboard",
    checkingSession: "Checking your session",
    footer: "© 2026 Meridian Group. Fictional project for portfolio.",
  },
  login: {
    title: "Sign in",
    lead: "For Aurora Residence sales managers.",
    email: "Email",
    password: "Password",
    submit: "Sign in",
    submitting: "Signing in",
    forgot: "Forgot password? Ask the site administrator.",
    emailInvalid: "Enter a valid email address",
    passwordRequired: "Enter your password",
    wrongCredentials: "Wrong email or password. {count} {attempts} left, then sign-in pauses for 15 minutes.",
    attemptOne: "attempt",
    attemptMany: "attempts",
    paused: "Too many failed attempts. Sign-in is paused, try again in {count} {minutes}.",
    minuteOne: "minute",
    minuteMany: "minutes",
    failed: "Could not reach the server. Check the connection and try again.",
  },
  nav: {
    label: "Admin sections",
    dashboard: "Dashboard",
    residences: "Residences",
    enquiries: "Enquiries",
    logout: "Log out",
    loggingOut: "Logging out",
  },
  roles: {
    ADMIN: "Administrator",
    MANAGER: "Sales manager",
  },
  placeholder: {
    title: "Coming in task 6b",
    text: "This section is not built yet. The dashboard already shows live numbers.",
    back: "Back to dashboard",
  },
  states: {
    loadFailed: "Could not load the data. Check the connection and try again.",
    retry: "Try again",
    loading: "Loading",
  },
  dashboard: {
    title: "Dashboard",
    subtitle: "{date}. Aurora Residence, {total} residences.",
    statsLabel: "Residence and enquiry totals",
    available: "Available",
    reserved: "Reserved",
    sold: "Sold",
    newToday: "New enquiries today",
    ofTotal: "of {total} residences",
    endingSoon: "{count} {reservations} end within 2 days",
    reservationOne: "reservation",
    reservationMany: "reservations",
    noneEndingSoon: "None end within 2 days",
    shareOfHouse: "{percent}% of the house",
    waitingForCall: "{count} still waiting for a call",
    shareLabel: "Available {available}, reserved {reserved}, sold {sold}",
  },
  facade: {
    title: "Facade",
    lead: "Live status of every residence",
    entrance: "Entrance",
    floor: "Floor {floor}",
    residence: "Residence {number}, {status}",
    legend: "{status} {count}",
    statuses: { AVAILABLE: "Available", RESERVED: "Reserved", SOLD: "Sold" },
  },
  reservations: {
    title: "Reservations ending soon",
    lead: "Each reservation lasts 7 days. Extend or release before it ends.",
    all: "All reserved",
    empty: "No active reservations right now.",
    ends: "Ends {date}",
    endsToday: "Ends today",
    dayOne: "1 day left",
    dayMany: "{count} days left",
    noClient: "No enquiry",
  },
  enquiries: {
    title: "Latest enquiries",
    lead: "{shown} of {total}. Enquiries never reserve a residence by themselves.",
    all: "All enquiries",
    empty: "No enquiries yet. New ones appear here as soon as they arrive.",
    today: "Today, {time}",
    yesterday: "Yesterday, {time}",
    residence: "Residence {number}",
    general: "General",
    studio: "Studio",
    bedrooms: "{count} bd",
    details: "{bedrooms}, {area} m², {price}",
    open: "Open",
    openLabel: "Open enquiry from {name}",
    statuses: { NEW: "New", IN_PROGRESS: "In progress", CLOSED: "Closed" },
    columns: {
      received: "Received",
      client: "Client",
      phone: "Phone",
      residence: "Residence",
      status: "Status",
      action: "Action",
    },
  },
};

export type AdminDictionary = typeof adminEn;

export function getAdminDictionary(): AdminDictionary {
  return adminEn;
}
