/** Enquiry list and enquiry card texts, part of the admin dictionary in en-admin.ts. */
export const enquiryListEn = {
  title: "Enquiries",
  lead: "{total} enquiries from the site. Call new ones within one working day; an enquiry never reserves a residence.",
  leadOne: "1 enquiry from the site. Call new ones within one working day; an enquiry never reserves a residence.",
  searchLabel: "Search enquiries by name, phone or email",
  searchPlaceholder: "Search by name, phone or email",
  statusFilter: "Filter by status",
  all: "All",
  residenceLabel: "Residence",
  anyResidence: "Any",
  newestFirst: "Newest first",
  tableLabel: "Enquiries, page {page} of {pages}",
  empty: "No enquiries match these filters.",
  emptyAll: "No enquiries yet. New ones appear here as soon as they arrive from the site.",
  reset: "Reset filters",
  pagination: "Pages",
  showing: "{from}-{to} of {total}",
  previous: "Previous",
  next: "Next",
  newLabel: "New enquiry",
};

export const enquiryEn = {
  back: "All enquiries",
  notFound: {
    title: "Enquiry not found",
    text: "It may have been removed, or the link is wrong.",
  },
  received: "Received {when}",
  receivedToday: "today at {time}",
  receivedYesterday: "yesterday at {time}",
  receivedOn: "on {date} at {time}",
  fromResidencePage: "from the page of residence {number}",
  aboutResidence: "about residence {number}",
  general: "General enquiry, no residence chosen",
  client: {
    title: "Client",
    name: "Name",
    phone: "Phone",
    email: "Email",
    locale: "Site language",
    currency: "Currency on site",
    source: "Source",
    locales: { en: "English", ru: "Russian" } as Record<string, string>,
  },
  comment: {
    title: "Comment from the client",
    empty: "The client left no comment.",
  },
  note: {
    title: "Manager note",
    lead: "Visible to managers only, never sent to the client.",
    label: "Manager note",
    tooLong: "Keep the note under 2000 characters.",
    save: "Save note",
    saving: "Saving",
    saved: "Note saved.",
    lastSaved: "Last saved {when} by {author}",
    never: "No note saved yet.",
  },
  activity: {
    title: "Activity",
    empty: "No activity yet.",
    received: "Enquiry received from the site",
    statusChanged: "Status changed: {from} → {to}",
    noteAdded: "Note added",
    residenceLinked: "Residence {number} linked to the enquiry",
    residenceStatus: "Residence {number}: {from} → {to}",
    residenceListed: "Residence {number}: {to}",
    priceChanged: "Residence {number}: price {from} → {to}",
  },
  status: {
    title: "Status",
    label: "Enquiry status",
    hint: "Close the enquiry when the deal is signed or the client says no.",
  },
  residence: {
    title: "Residence",
    name: "Residence {number}",
    specs: "Floor {floor}  ·  {bedrooms}  ·  {area} m²  ·  {price}",
    open: "Open residence {number}",
    reserve: "Reserve for 7 days",
    reserving: "Reserving",
    reserveHint: "Reserves {number} for this client for 7 days. The site shows it as Reserved at once.",
    reservedHere: "Reserved for this client until {date}. The residence returns to Available by itself if there is no deal.",
    reservedElse: "Residence {number} is already reserved for another client. Reserve it after that reservation ends or is released.",
    sold: "Residence {number} is sold and cannot be reserved.",
    closed: "This enquiry is closed. Set it back to In progress to reserve the residence.",
    confirmTitle: "Reserve {number} for {client}?",
    confirmText: "The residence becomes Reserved on the site at once. The reservation ends on {date} unless you release it or sell the residence.",
    confirmStatus: "The enquiry moves from New to In progress.",
  },
  link: {
    lead: "The client did not choose a residence. Link one after the call to make a reservation possible.",
    label: "Residence number",
    placeholder: "For example, 7.03",
    invalid: "Enter a residence number from 1.01 to 11.06, for example 7.03.",
    submit: "Link residence",
    linking: "Linking",
    confirmTitle: "Link residence {number} to this enquiry?",
    confirmText: "The enquiry stops being General. The status of {number} on the site does not change.",
    confirm: "Link",
    linked: "Residence {number} is linked to the enquiry.",
  },
  cancel: "Cancel",
  errors: {
    reserveConflict: "Residence {number} cannot be reserved: it is no longer available, someone reserved or sold it a moment ago. The card now shows the current state.",
    reserveRejected: "This enquiry cannot be used for the reservation. {detail}",
    linkMissing: "There is no residence {number} in the house. Numbers go from 1.01 to 11.06.",
    linkSold: "Residence {number} is sold, link another residence.",
    linkTaken: "The enquiry already has a residence, someone linked it a moment ago. The card now shows it.",
    rejected: "The change was not accepted. Check the values and try again.",
    conflict: "Someone changed this enquiry a moment ago. The card now shows the current state; check it and try again.",
    failed: "Could not save. Check the connection and try again.",
  },
};
