/** Texts of the home enquiry form and of sending any enquiry. Merged into the English dictionary. */
export const enquiryEn = {
  enquiry: {
    overline: "Private viewing",
    title: "Visit the sales gallery",
    lead: "Leave your details and a sales manager will call you back within one working day to arrange a viewing or send you floor plans and prices.",
    phoneTitle: "Phone",
    emailTitle: "Email",
    emailNote: "Reply within a day",
    galleryTitle: "Sales gallery",
    galleryPlace: "At the main entrance",
    galleryNote: "Viewings by appointment",
    formTitle: "Request a call back",
    name: "Name",
    namePlaceholder: "Your name",
    phone: "Phone",
    countryCode: "Country code",
    codePlaceholder: "Code",
    phoneNumber: "Phone number",
    email: "Email",
    emailPlaceholder: "name@example.com",
    website: "Website",
    submit: "Request a call back",
    errors: {
      name: "Enter your name",
      code: "Choose a country code",
      phone: "Enter a phone number with 7 to 15 digits including the code",
      email: "Enter a valid email address",
    },
    countries: [
      ["+1", "United States, Canada"],
      ["+44", "United Kingdom"],
      ["+49", "Germany"],
      ["+33", "France"],
      ["+34", "Spain"],
      ["+39", "Italy"],
      ["+31", "Netherlands"],
      ["+41", "Switzerland"],
      ["+48", "Poland"],
      ["+90", "Turkey"],
      ["+971", "United Arab Emirates"],
      ["+972", "Israel"],
      ["+7", "Kazakhstan, Russia"],
      ["+998", "Uzbekistan"],
      ["+996", "Kyrgyzstan"],
      ["+995", "Georgia"],
      ["+374", "Armenia"],
      ["+994", "Azerbaijan"],
      ["+86", "China"],
      ["+91", "India"],
      ["+65", "Singapore"],
      ["+61", "Australia"],
    ] as [string, string][],
  },
  enquirySend: {
    consentBefore: "I agree to the processing of my personal data for this request, as described in the ",
    privacy: "Privacy policy",
    consentAfter: ".",
    consentError: "Please agree to the processing of your data",
    sending: "Sending",
    rateLimited: "Too many requests from this device. Please try again later.",
    failedBefore: "Something went wrong while sending your request. Please try again or call ",
    failedAfter: ".",
    soldRejected: "This residence has just been sold. Please choose another one.",
    residenceMissing: "This residence is not in the house. Please choose another one.",
    success: {
      overline: "Request sent",
      title: "Thank you",
      leadResidence: "Your request for residence {number} is with our sales team.",
      lead: "Your request is with our sales team.",
      nextTitle: "What happens next",
      stepCall: "A sales manager calls you within one working day to answer your questions and arrange a viewing.",
      stepReserve: "If you decide to go ahead, the manager reserves residence {number} for you for 7 days.",
      stepReserved: "Residence {number} is reserved by another buyer. If that reservation ends without a deal, the manager calls you first.",
      stepChoose: "The manager helps you choose a residence and can reserve it for you for 7 days.",
      available: "Stays available until you decide",
      reserved: "Held for another buyer for now",
      backToResidences: "Back to residences",
      chooseResidence: "Choose your residence",
      questionsBefore: "Questions right now? Call ",
      questionsAfter: ".",
    },
  },
};
