/** Texts of the residence selection pages: facade, filters, floor plan. Merged into the English dictionary. */
export const residencesEn = {
  residences: {
    metaTitle: "Choose your residence · Aurora Residence",
    overline: "Residences",
    title: "Choose your residence",
    lead: "Sixty-six residences on eleven floors. Hover a floor to see what is free, click it to open the plan.",
    leadList:
      "All residences in one list. Sort by price or area and open any residence for its plan, view and instalment plan.",
    leadGrid:
      "Every residence of the house in one view: floors from top to bottom, six residences on each. Hover a cell for details, click it to open the residence.",
    loading: "Loading live availability",
    hintPointer: "Click to open the plan",
    hintTouch: "Tap a floor to select it",
    floorSelected: "Floor {floor} selected, {availability}",
    openFloorPlan: "Open floor {floor} plan",
    openFloor: "Open floor {floor}",
    floorSelectedOverline: "Floor selected",
    available: "Available",
    availableShort: "{available} of {total}",
    price: "Price",
    floorBelow: "Floor below",
    floorAbove: "Floor above",
    residencesOnFloor: "Residences on floor {floor}",
    noMatches: "No residences match these filters. Try a higher price or another floor.",
    resetFilters: "Reset filters",
    viewUnavailable:
      "Live availability is not reachable right now, so the residences cannot be shown. Please refresh the page in a minute or call +1 (555) 010-2040.",
    unavailable:
      "Live availability is not reachable right now, so the facade is shown without numbers. Please refresh in a minute or call +1 (555) 010-2040.",
    comingSoon: {
      grid: "The floor grid is coming soon",
      list: "The list of residences is coming soon",
      text: "Every residence of the house in one view is on its way. Meanwhile, choose your floor on the facade.",
      back: "Choose on the facade",
    },
  },
  grid: {
    title: "Floor grid: {count} residences, floors from top to bottom",
    floor: "Floor",
    column: ".{position}  {type}",
    floorLabel: "Floor {floor}",
    info: "{bedrooms} · {area}",
    cellLabel: "Residence {number}, {type}, {price}, {status}",
    mutedNote: "Muted residences do not match the filters.",
    note: "Prices in USD, availability updates live.",
    summaryOverline: "Whole house",
    summaryTitle: "Availability",
    yourFilters: "Your filters",
    filtersText: "{type}, {floor}, {price}",
    anyType: "Any size",
    anyFloor: "any floor",
    floorNumber: "floor {floor}",
    matching: "Matching residences",
    availableNow: "Available now",
    pricesFrom: "Prices from",
    noneAvailable: "None available",
    showInList: "Show {count} in list",
  },
  list: {
    title: "Residences matching the filters",
    heading: "{count} {noun}, {available} available",
    headingShort: "{count} {noun}",
    availableCount: "{available} available",
    nouns: {
      any: ["residence", "residences"],
      byBedrooms: [
        ["studio", "studios"],
        ["one-bedroom residence", "one-bedroom residences"],
        ["two-bedroom residence", "two-bedroom residences"],
        ["three-bedroom residence", "three-bedroom residences"],
      ],
    },
    sortBy: "Sort by",
    sortOptions: {
      available: "Available first",
      "price-asc": "Price, low to high",
      "price-desc": "Price, high to low",
      "area-desc": "Area, large first",
    },
    columns: {
      plan: "Plan",
      residence: "Residence",
      floor: "Floor",
      bedrooms: "Bedrooms",
      area: "Area",
      price: "Price",
      status: "Status",
      action: "Open",
    },
    sortByColumn: "Sort by {column}",
    residence: "Residence {number}",
    description: "{type}, {side}, {view}",
    sides: { north: "north", south: "south", east: "east", west: "west" },
    floorOf: "Floor {floor} of {total}",
    details: "Details",
    detailsOf: "Details of residence {number}",
    planOf: "Plan of residence {number}",
    showing: "Showing {shown} of {total}",
    showMore: "Show more",
  },
  filters: {
    label: "Filter residences",
    bedrooms: "Bedrooms",
    bedroomsAll: "All",
    bedroomOptions: ["Studio", "1 bd", "2 bd", "3 bd"],
    price: "Price, USD",
    priceRange: "{min} - {max}",
    anyPrice: "Any price",
    floor: "Floor",
    anyFloor: "Any floor",
    floorOption: "Floor {floor}",
    resultAll: "{available} of {total} available",
    resultFiltered: "{matching} of {total} match, {available} available",
    reset: "Reset",
    open: "Filters",
    openWithCount: "Filters · {count}",
    title: "Filters",
    show: "Show residences",
    close: "Close filters",
  },
  floorPage: {
    metaTitle: "Floor {floor} plan · Aurora Residence",
    loading: "Loading the floor plan",
    back: "Back to facade",
    backShort: "Facade",
    overline: "Residences / Floor plan",
    title: "Floor {floor}",
    summary: "{available} of {total} residences available, from {price}",
    summarySoldOut: "All {total} residences on this floor are sold or reserved",
    floorLabel: "Floor",
    floorOf: "{floor} of {total}",
    neighbour: "Floor {floor}: {available} available",
    floorBelow: "Floor below",
    floorAbove: "Floor above",
    planTitle: "Floor {floor} plan, {count} residences",
    planLabel: "Plan of floor {floor}. Residences are coloured by status.",
    north: "N",
    southFacade: "South facade, park side",
    scale: "5 m",
    onThisFloor: "On this floor",
    residencesCount: "{count} residences",
    columns: { number: "No.", bedrooms: "Bedrooms", area: "Area", price: "Price", status: "Status" },
    studio: "Studio",
    bedroomsShort: "{count} bd",
    typeNames: ["Studio", "One-bedroom", "Two-bedroom", "Three-bedroom"],
    typeArea: "{type}, {area}",
    area: "{area} m²",
    penthouse: "Penthouse, incl. terrace",
    residence: "Residence {number}",
    clickToOpen: "Click to open",
    notForSale: "Sold, not available",
    note: "Prices in USD at fixed exchange rates. Availability updates live, the moment a residence is reserved.",
    openResidence: "Open residence {number}",
    availableOf: "{available} of {total} available",
    unavailable:
      "We could not load this floor right now. Please refresh the page in a minute or call +1 (555) 010-2040.",
  },
  notFound: {
    metaTitle: "Page not found · Aurora Residence",
    overline: "Error 404",
    title: "This page does not exist",
    text: "The link may be outdated or mistyped. The residences and the facade are one click away.",
    home: "Back to home",
    residences: "Choose a residence",
  },
};
