/** Texts of the residence page /residences/<number> and its enquiry form. Merged into the English dictionary. */
export const residenceEn = {
  residencePage: {
    metaTitle: "Residence {number} · {type}, {area} · Aurora Residence",
    metaTitleShort: "Residence {number} · Aurora Residence",
    metaDescription:
      "{type} residence {number} on floor {floor} of Aurora Residence: {area}, {view} view, {price}. Plan with room areas, interest-free instalment plan and a direct request to the sales manager.",
    metaDescriptionSold:
      "{type} residence {number} on floor {floor} of Aurora Residence: {area}, {view} view. This residence is sold; see similar residences that are still available.",
    loading: "Loading the residence",
    backToFloor: "Back to floor {floor}",
    backShort: "Floor {floor}",
    breadcrumbs: "Breadcrumbs",
    crumbResidences: "Residences",
    crumbFloor: "Floor {floor}",
    crumbResidence: "Residence {number}",
    updatedLive: "Updated live",
    title: "Residence {number}",
    descriptions: [
      "Studio with a bright living area, a kitchen wall and a bathroom by the entrance.",
      "One-bedroom residence with a separate bedroom and a living room with a kitchen.",
      "Two-bedroom residence with an en-suite and a living room facing the park.",
      "Three-bedroom corner residence with windows on three sides and a large living room.",
    ],
    floor: "Floor",
    floorOf: "{floor} of {total}",
    bedrooms: "Bedrooms",
    area: "Area",
    view: "View",
    ceiling: "Ceiling height",
    ceilingValue: "{height} m",
    price: "Price",
    pricePerMetre: "{perMetre} per m², or from {monthly} a month with the instalment plan",
    request: "Request this residence",
    requestNote:
      "A sales manager calls you within one working day and, if you decide, reserves the residence for you for 7 days.",
    reservedTitle: "Reserved by another buyer",
    reservedNote:
      "Another buyer holds this residence for up to 7 days. You can still leave a request: if the reservation ends without a deal, the sales manager calls you first.",
    soldTitle: "This residence is sold",
    soldNote: "It stays on the site so you can compare layouts. These residences are still available:",
    soldOnFloor: "Available on floor {floor}",
    soldSimilar: "The same layout on other floors",
    soldNone: "No residences of this layout are available right now.",
    soldAll: "See all available residences",
    residenceShort: "Residence {number}",
    unavailable:
      "We could not load this residence right now. Please refresh the page in a minute or call +1 (555) 010-2040.",
    plan: {
      title: "Plan, {area}",
      label: "Plan of residence {number} with room areas",
      north: "N",
      entrance: "Entrance",
      windows: "Windows face {side}, onto the {view}",
      ceiling: "Ceiling height {height} m",
      terrace: "Terrace {area} on the roof, not shown on the plan",
      rooms: "Rooms",
    },
    rooms: {
      studio: "Living area and kitchen",
      living: "Living room and kitchen",
      master: "Master bedroom",
      bedroom: "Bedroom",
      ensuite: "En-suite",
      hall: "Hall",
      bath: "Bath",
      entrance: "Entry",
      terrace: "Terrace",
    },
    position: {
      title: "On floor {floor}",
      label: "Position of residence {number} on the plan of floor {floor}",
      open: "Open floor {floor} plan",
      sides: { north: "north side", south: "south side, park", east: "east end", west: "west end" },
    },
    windowView: {
      overline: "View from the window",
      title: "The park, {floors} below",
      floorWords: [
        "one floor",
        "two floors",
        "three floors",
        "four floors",
        "five floors",
        "six floors",
        "seven floors",
        "eight floors",
        "nine floors",
        "ten floors",
        "eleven floors",
      ],
      textExact: "Rendered from the living room of {number}, {height} m above the ground.",
      textOther:
        "Rendered from the living room of 7.03, 24 m above the ground. Residence {number} is {height} m above the ground and looks onto the same park.",
      alt: "Sunset over the park and the city from a living room window",
    },
    instalments: {
      overline: "Instalment plan",
      title: "Interest free, straight from the developer",
      text: "Pay part of the price now and the rest in equal monthly payments, with no bank and no interest.",
      downPayment: "Down payment",
      term: "Term",
      months: "{count} months",
      monthly: "Monthly payment",
      monthlyNote: "for {months} months, 0% interest",
      price: "Price",
      downPaymentRow: "Down payment, {percent}%",
      instalmentsRow: "Paid in instalments",
      disclaimer: "Indicative calculation in USD. The final schedule is fixed in the sales agreement.",
    },
    similar: {
      overline: "Same layout, other floors",
      title: "Similar residences",
      all: "All residences",
      swipe: "Swipe to see more",
      details: "Details",
    },
  },
  residenceEnquiry: {
    overline: "Enquiry",
    title: "Request this residence",
    lead: "Leave your details and a sales manager will call you back to arrange a viewing.",
    yourResidence: "Your residence",
    summary: "{bedrooms}  ·  {area}  ·  Floor {floor} of {total}  ·  {price}",
    nameLabel: "Full name",
    emailPlaceholder: "you@example.com",
    comment: "Comment, optional",
    commentPlaceholder: "Questions or a convenient time to call",
    consentBefore: "I agree to the processing of my personal data for this request, as described in the ",
    privacy: "Privacy policy",
    consentAfter: ".",
    submit: "Send request",
    replyNote: "A sales manager replies within one working day.",
    close: "Close the enquiry",
    errors: {
      comment: "Keep the comment under 2000 characters",
      consent: "Please agree to the processing of your data",
    },
    checked:
      "Thank you, the details are correct. Online requests open very soon; until then, please call +1 (555) 010-2040 and name residence {number}.",
  },
};
