/** Texts of the residence selection pages: facade, filters, floor plan. Merged into the English dictionary. */
export const residencesEn = {
  residences: {
    metaTitle: "Choose your residence · Aurora Residence",
    overline: "Residences",
    title: "Choose your residence",
    lead: "Sixty-six residences on eleven floors. Hover a floor to see what is free, click it to open the plan.",
    loading: "Loading live availability",
    hintPointer: "Click to open the plan",
    hintTouch: "Tap a floor to select it",
    floorSelected: "Floor {floor} selected, {availability}",
    openFloorPlan: "Open floor {floor} plan",
    openFloor: "Open floor {floor}",
    floorSelectedOverline: "Floor selected",
    available: "Available",
    availableShort: "{available} of {total}",
    price: "Price",
    floorBelow: "Floor below",
    floorAbove: "Floor above",
    residencesOnFloor: "Residences on floor {floor}",
    noMatches: "No residences match these filters. Try a higher price or another floor.",
    unavailable:
      "Live availability is not reachable right now, so the facade is shown without numbers. Please refresh in a minute or call +1 (555) 010-2040.",
    comingSoon: {
      grid: "The floor grid is coming soon",
      list: "The list of residences is coming soon",
      text: "Every residence of the house in one view is on its way. Meanwhile, choose your floor on the facade.",
      back: "Choose on the facade",
    },
  },
  filters: {
    label: "Filter residences",
    bedrooms: "Bedrooms",
    bedroomsAll: "All",
    bedroomOptions: ["Studio", "1 bd", "2 bd", "3 bd"],
    price: "Price, USD",
    priceRange: "{min} - {max}",
    anyPrice: "Any price",
    floor: "Floor",
    anyFloor: "Any floor",
    floorOption: "Floor {floor}",
    resultAll: "{available} of {total} available",
    resultFiltered: "{matching} of {total} match, {available} available",
    reset: "Reset",
    open: "Filters",
    openWithCount: "Filters · {count}",
    title: "Filters",
    show: "Show residences",
    close: "Close filters",
  },
  floorPage: {
    metaTitle: "Floor {floor} plan · Aurora Residence",
    loading: "Loading the floor plan",
    back: "Back to facade",
    backShort: "Facade",
    overline: "Residences / Floor plan",
    title: "Floor {floor}",
    summary: "{available} of {total} residences available, from {price}",
    summarySoldOut: "All {total} residences on this floor are sold or reserved",
    floorLabel: "Floor",
    floorOf: "{floor} of {total}",
    neighbour: "Floor {floor}: {available} available",
    floorBelow: "Floor below",
    floorAbove: "Floor above",
    planTitle: "Floor {floor} plan, {count} residences",
    planLabel: "Plan of floor {floor}. Residences are coloured by status.",
    north: "N",
    southFacade: "South facade, park side",
    scale: "5 m",
    onThisFloor: "On this floor",
    residencesCount: "{count} residences",
    columns: { number: "No.", bedrooms: "Bedrooms", area: "Area", price: "Price", status: "Status" },
    studio: "Studio",
    bedroomsShort: "{count} bd",
    typeNames: ["Studio", "One-bedroom", "Two-bedroom", "Three-bedroom"],
    typeArea: "{type}, {area}",
    area: "{area} m²",
    penthouse: "Penthouse, incl. terrace",
    residence: "Residence {number}",
    clickToOpen: "Click to open",
    notForSale: "Sold, not available",
    note: "Prices in USD at fixed exchange rates. Availability updates live, the moment a residence is reserved.",
    openResidence: "Open residence {number}",
    availableOf: "{available} of {total} available",
    unavailable:
      "We could not load this floor right now. Please refresh the page in a minute or call +1 (555) 010-2040.",
  },
  notFound: {
    metaTitle: "Page not found · Aurora Residence",
    overline: "Error 404",
    title: "This page does not exist",
    text: "The link may be outdated or mistyped. The residences and the facade are one click away.",
    home: "Back to home",
    residences: "Choose a residence",
  },
};
