import { pluralForms } from "@/lib/plural";

import type { AdminDictionary } from "./en-admin";
import { enquiryListRu, enquiryRu } from "./ru-admin-enquiries";
import { messagesRu } from "./ru-admin-messages";

export const adminRu: AdminDictionary = {
  locale: {
    lang: "ru",
    intl: "ru-RU",
  },
  meta: {
    title: "Отдел продаж | Aurora Residence",
    loginTitle: "Вход | Aurora Residence",
    residenceTitle: "Квартира {number} | Отдел продаж",
    enquiriesTitle: "Заявки | Отдел продаж",
    enquiryTitle: "Заявка | Отдел продаж",
  },
  common: {
    salesAdmin: "Отдел продаж",
    home: "Aurora Residence, обзор",
    checkingSession: "Проверяем вход",
    language: "Язык",
    languages: { en: "EN", ru: "RU" },
    footer: "© 2026 Meridian Group. Вымышленный проект для портфолио.",
  },
  login: {
    title: "Вход",
    lead: "Для менеджеров по продажам Aurora Residence.",
    email: "Почта",
    password: "Пароль",
    submit: "Войти",
    submitting: "Входим",
    forgot: "Забыли пароль? Обратитесь к администратору сайта.",
    emailInvalid: "Введите корректный адрес почты",
    passwordRequired: "Введите пароль",
    wrongCredentials: "Неверная почта или пароль. Осталось {attempts}, потом вход приостановится на 15 минут.",
    attempts: pluralForms("{count} попытка", "{count} попытки", "{count} попыток"),
    paused: "Слишком много неудачных попыток. Вход приостановлен, попробуйте через {minutes}.",
    minutes: pluralForms("{count} минуту", "{count} минуты", "{count} минут"),
    failed: "Не удалось связаться с сервером. Проверьте соединение и попробуйте ещё раз.",
  },
  nav: {
    label: "Разделы админки",
    dashboard: "Обзор",
    residences: "Квартиры",
    enquiries: "Заявки",
    logout: "Выйти",
    loggingOut: "Выходим",
  },
  live: {
    open: "Онлайн: изменения сразу на сайте",
    offline: "Нет связи: подключаемся",
    offlineShort: "Нет связи",
  },
  roles: {
    ADMIN: "Администратор",
    MANAGER: "Менеджер по продажам",
  },
  states: {
    loadFailed: "Не удалось загрузить данные. Проверьте соединение и попробуйте ещё раз.",
    retry: "Повторить",
    loading: "Загрузка",
  },
  dashboard: {
    title: "Обзор",
    subtitle: "{date}. Aurora Residence, {residences}.",
    residences: pluralForms("{count} квартира", "{count} квартиры", "{count} квартир"),
    statsLabel: "Итоги по квартирам и заявкам",
    available: "Свободно",
    reserved: "Бронь",
    sold: "Продано",
    newToday: "Новые заявки сегодня",
    ofTotal: "из {total} квартир",
    endingSoon: pluralForms(
      "{count} бронь истекает за 2\u00a0дня",
      "{count} брони истекают за 2\u00a0дня",
      "{count} броней истекают за 2\u00a0дня",
    ),
    noneEndingSoon: "За 2\u00a0дня ничего не истекает",
    shareOfHouse: "{percent}% дома",
    waitingForCall: pluralForms("{count} ждёт звонка", "{count} ждут звонка", "{count} ждут звонка"),
    shareLabel: "Свободно {available}, бронь {reserved}, продано {sold}",
  },
  facade: {
    title: "Фасад",
    lead: "Статус каждой квартиры в реальном времени",
    entrance: "Вход",
    floor: "Этаж {floor}",
    residence: "Квартира {number}, {status}",
    legend: "{status} {count}",
    statuses: { AVAILABLE: "Свободна", RESERVED: "Бронь", SOLD: "Продана" },
  },
  reservations: {
    title: "Брони, которые скоро истекут",
    lead: "Бронь действует 7 дней. Продлите или снимите её до окончания.",
    all: "Все брони",
    empty: "Активных броней сейчас нет.",
    ends: "До {date}",
    endsToday: "Истекает сегодня",
    daysLeft: pluralForms("Истекает через {count} день", "Истекает через {count} дня", "Истекает через {count} дней"),
    noClient: "Без заявки",
  },
  residences: {
    title: "Квартиры",
    lead: "{total} квартир на {floors} этажах. Изменения появляются на сайте сразу после сохранения.",
    totals: "Итоги по дому",
    totalAvailable: "Свободно {count}",
    totalReserved: "Бронь {count}",
    totalSold: "Продано {count}",
    searchLabel: "Поиск по номеру квартиры",
    searchPlaceholder: "Номер, например 7.03",
    floorLabel: "Этаж",
    allFloors: "Все",
    floorOption: "Этаж {floor}",
    statusFilter: "Фильтр по статусу",
    all: "Все",
    showing: "Показано {shown} из {total}",
    tableLabel: "Квартиры, показано {shown}",
    columns: {
      residence: "Квартира",
      floor: "Этаж",
      bedrooms: "Спальни",
      area: "Площадь, м²",
      price: "Цена, USD",
      status: "Статус",
      updated: "Изменено",
      action: "Действие",
    },
    studio: "Студия",
    penthouse: "Пентхаус, с террасой",
    brief: "{bedrooms}, {area}\u00a0м²",
    bedroomsShort: "{count} сп.",
    open: "Открыть",
    openLabel: "Открыть квартиру {number}",
    empty: "Нет квартир по этим фильтрам.",
    reset: "Сбросить фильтры",
  },
  residence: {
    back: "Все квартиры",
    title: "Квартира {number}",
    summary: "Этаж {floor} из {floors}",
    bedrooms: pluralForms("{count} спальня", "{count} спальни", "{count} спален"),
    studio: "Студия",
    area: "{area}\u00a0м²",
    penthouse: "Пентхаус, с террасой",
    viewOnSite: "Открыть на сайте",
    viewOnSiteLabel: "Открыть квартиру {number} на сайте в новой вкладке",
    planLabel: "План квартиры {number}",
    specs: {
      floor: "Этаж",
      floorValue: "{floor} из {floors}",
      bedrooms: "Спальни",
      area: "Площадь",
      layout: "Планировка",
      ceiling: "Высота потолков",
      ceilingValue: "{height}\u00a0м",
      view: "Вид",
    },
    places: {
      1: "север, у ядра слева",
      2: "север, у ядра справа",
      3: "юг, левее центра",
      4: "юг, правее центра",
      5: "западный торец, окна на две стороны",
      6: "восточный торец, окна на две стороны",
    },
    sides: { NORTH: "Север", SOUTH: "Юг", WEST: "Запад", EAST: "Восток" },
    views: { courtyard: "Двор", park: "Парк", "park and city": "Парк и город" },
    priceStatus: {
      title: "Цена и статус",
      lead: "Сохранённые изменения сразу появляются во всех открытых вкладках сайта.",
      price: "Цена, USD",
      priceInvalid: "Введите целую сумму от 10 000 $ до 10 000 000 $.",
      status: "Статус",
      statusLabel: "Статус квартиры {number}",
      reservedOnlyFromEnquiry: "Бронь ставится из заявки",
      save: "Сохранить",
      saving: "Сохраняем",
      cancel: "Отмена",
      unchanged: "Сохранять нечего: измените цену или статус.",
      saved: "Сохранено. Сайт показывает новые значения.",
    },
    confirm: {
      title: "Сохранить изменения {number}?",
      price: "Цена {from} → {to}",
      status: "Статус {from} → {to}",
      releaseNote: "Активная бронь сразу снимается.",
      soldNote: "Активная бронь закрывается продажей.",
      note: "Комментарий для истории (необязательно)",
      notePlaceholder: "Например, осенний прайс",
      confirm: "Подтвердить",
      cancel: "Отмена",
    },
    reservation: {
      title: "Бронь",
      lead: "Бронируйте после звонка, когда клиент решил. Квартира сама вернётся в свободные, когда бронь истечёт.",
      none: "Активной брони нет.",
      soldNote: "Проданную квартиру нельзя забронировать.",
      client: "Заявка",
      noEnquiry: "Без заявки",
      ends: "Бронь до",
      reservedBy: "Бронь: {author}, {date}",
      release: "Снять бронь",
      releasing: "Снимаем",
      releaseTitle: "Снять бронь с {number}?",
      releaseText: "Бронь {client} снимется сейчас. Квартира сразу станет свободной на сайте.",
      releaseConfirm: "Снять",
      released: "Бронь снята. Квартира снова свободна.",
      enquiryLabel: "Заявка",
      enquiryOption: "{name}, {received}",
      endsHint: "7 дней с момента брони",
      reserve: "Забронировать на 7 дней",
      reserving: "Бронируем",
      reserveNote: "Фасад, план этажа и список на сайте сразу покажут бронь.",
      noOpenEnquiries:
        "По квартире {number} нет открытых заявок. Бронь ставится по заявке на эту квартиру: сначала привяжите её к общей заявке.",
      reserveTitle: "Забронировать {number} для {client}?",
      reserveText: "Квартира сразу станет забронированной на сайте. Бронь действует до {date}, если её не снять и не продать квартиру.",
      reserveStatus: "Заявка перейдёт из статуса «Новая» в «В работе».",
    },
    enquiries: {
      title: "Заявки на {number}",
      empty: "По этой квартире заявок пока нет.",
      failed: "Не удалось загрузить заявки.",
      openLabel: "Открыть заявку {name}",
    },
    history: {
      title: "История статуса и цены",
      empty: "Изменений пока нет.",
      failed: "Не удалось загрузить историю.",
      label: "{from} на {to}",
    },
    errors: {
      conflict: "Квартиру только что изменили. Карточка показывает текущее состояние: проверьте и попробуйте ещё раз.",
      rejected: "Изменение не принято. Проверьте значения и попробуйте ещё раз.",
      failed: "Не удалось сохранить. Проверьте соединение и попробуйте ещё раз.",
    },
    notFound: {
      title: "Квартира не найдена",
      text: "Такой квартиры в доме нет. Номера идут от 1.01 до 11.06.",
    },
  },
  enquiries: {
    title: "Последние заявки",
    lead: "{shown} из {total}. Заявка сама никогда не ставит бронь.",
    all: "Все заявки",
    empty: "Заявок пока нет. Новые появятся здесь сразу после отправки.",
    today: "Сегодня в {time}",
    yesterday: "Вчера в {time}",
    earlier: "{date}, {time}",
    residence: "Квартира {number}",
    general: "Общая",
    studio: "Студия",
    bedrooms: "{count} сп.",
    details: "{bedrooms}, {area}\u00a0м², {price}",
    open: "Открыть",
    openLabel: "Открыть заявку {name}",
    statuses: { NEW: "Новая", IN_PROGRESS: "В работе", CLOSED: "Закрыта" },
    columns: {
      received: "Получена",
      client: "Клиент",
      phone: "Телефон",
      residence: "Квартира",
      status: "Статус",
      action: "Действие",
    },
  },
  enquiryList: enquiryListRu,
  enquiry: enquiryRu,
  messages: messagesRu,
};
