import { pluralForms } from "@/lib/plural";

import type { residencesEn } from "./en-residences";

/** Russian texts of the residence selection pages: facade, floor grid, list, filters, floor plan. */
export const residencesRu: typeof residencesEn = {
  residences: {
    metaTitle: "Выбор квартиры · Aurora Residence",
    overline: "Квартиры",
    title: "Выберите квартиру",
    lead: "Шестьдесят шесть квартир на одиннадцати этажах. Наведите курсор на этаж, чтобы увидеть свободные, и нажмите, чтобы открыть план.",
    leadList:
      "Все квартиры одним списком. Сортируйте по цене или площади и открывайте любую, чтобы увидеть план, вид из окна и рассрочку.",
    leadGrid:
      "Все квартиры дома на одном экране: этажи сверху вниз, по шесть квартир на каждом. Наведите курсор на ячейку, чтобы увидеть детали, и нажмите, чтобы открыть квартиру.",
    loading: "Загружаем актуальное наличие",
    hintPointer: "Нажмите, чтобы открыть план",
    hintTouch: "Нажмите на этаж, чтобы выбрать его",
    floorSelected: "Выбран этаж {floor}, {availability}",
    openFloorPlan: "Открыть план этажа {floor}",
    openFloor: "Открыть этаж {floor}",
    floorSelectedOverline: "Выбран этаж",
    available: "Свободно",
    availableShort: "{available} из {total}",
    price: "Цена",
    floorBelow: "Этаж ниже",
    floorAbove: "Этаж выше",
    residencesOnFloor: "Квартиры на этаже {floor}",
    noMatches: "Под эти фильтры квартир нет. Попробуйте цену выше или другой этаж.",
    resetFilters: "Сбросить фильтры",
    viewUnavailable:
      "Сейчас не удаётся получить актуальное наличие, поэтому квартиры не показаны. Обновите страницу через минуту или позвоните +1 (555) 010-2040.",
    unavailable:
      "Сейчас не удаётся получить актуальное наличие, поэтому фасад показан без цифр. Обновите страницу через минуту или позвоните +1 (555) 010-2040.",
  },
  grid: {
    title: pluralForms(
      "Шахматка: {count} квартира, этажи сверху вниз",
      "Шахматка: {count} квартиры, этажи сверху вниз",
      "Шахматка: {count} квартир, этажи сверху вниз",
    ),
    floor: "Этаж",
    column: ".{position}  {type}",
    floorLabel: "Этаж {floor}",
    info: "{bedrooms} · {area}",
    cellLabel: "Квартира {number}, {type}, {price}, {status}",
    mutedNote: "Приглушённые квартиры не подходят под фильтры.",
    note: "Цены в {currency}, наличие обновляется вживую.",
    summaryOverline: "Весь дом",
    summaryTitle: "Наличие",
    yourFilters: "Ваши фильтры",
    filtersText: "{type}, {floor}, {price}",
    anyType: "Любая планировка",
    anyFloor: "любой этаж",
    floorNumber: "этаж {floor}",
    matching: "Подходят",
    availableNow: "Свободно сейчас",
    pricesFrom: "Цены от",
    noneAvailable: "Свободных нет",
    showInList: "Показать {count} в списке",
  },
  list: {
    title: "Квартиры по фильтрам",
    heading: "{count} {noun}, свободно {available}",
    headingShort: "{count} {noun}",
    availableCount: "Свободно {available}",
    nouns: {
      any: pluralForms("квартира", "квартиры", "квартир"),
      byBedrooms: [
        pluralForms("студия", "студии", "студий"),
        pluralForms("квартира с одной спальней", "квартиры с одной спальней", "квартир с одной спальней"),
        pluralForms("квартира с двумя спальнями", "квартиры с двумя спальнями", "квартир с двумя спальнями"),
        pluralForms("квартира с тремя спальнями", "квартиры с тремя спальнями", "квартир с тремя спальнями"),
      ],
    },
    sortBy: "Сортировка",
    sortOptions: {
      available: "Сначала свободные",
      "price-asc": "Сначала дешевле",
      "price-desc": "Сначала дороже",
      "area-desc": "Сначала просторные",
    },
    columns: {
      plan: "План",
      residence: "Квартира",
      floor: "Этаж",
      bedrooms: "Спальни",
      area: "Площадь",
      price: "Цена",
      status: "Статус",
      action: "Открыть",
    },
    sortByColumn: "Сортировать по столбцу «{column}»",
    residence: "Квартира {number}",
    description: "{type}, {side}, {view}",
    sides: { north: "север", south: "юг", east: "восток", west: "запад" },
    views: { courtyard: "двор", park: "парк", "park and city": "парк и город" },
    floorOf: "Этаж {floor} из {total}",
    details: "Подробнее",
    detailsOf: "Подробнее о квартире {number}",
    planOf: "План квартиры {number}",
    showing: "Показано {shown} из {total}",
    showMore: "Показать ещё",
    activeFilters: "Активные фильтры",
    chips: {
      bedrooms: ["Студия", "1 спальня", "2 спальни", "3 спальни"],
      price: "До {price}",
      floor: "Этаж {floor}",
      remove: "Убрать фильтр: {label}",
    },
  },
  filters: {
    label: "Фильтр квартир",
    bedrooms: "Спальни",
    bedroomsAll: "Все",
    bedroomOptions: ["Студия", "1 сп.", "2 сп.", "3 сп."],
    price: "Цена, {currency}",
    priceRange: "{min} - {max}",
    anyPrice: "Любая цена",
    floor: "Этаж",
    anyFloor: "Любой этаж",
    floorOption: "Этаж {floor}",
    resultAll: "Свободно {available} из {total}",
    resultFiltered: "Подходят {matching} из {total}, свободно {available}",
    reset: "Сбросить",
    open: "Фильтры",
    openWithCount: "Фильтры · {count}",
    title: "Фильтры",
    show: "Показать квартиры",
    close: "Закрыть фильтры",
  },
  floorPage: {
    metaTitle: "План этажа {floor} · Aurora Residence",
    loading: "Загружаем план этажа",
    back: "Назад к фасаду",
    backShort: "Фасад",
    overline: "Квартиры / План этажа",
    title: "Этаж {floor}",
    summary: "Свободно {available} из {total}, от {price}",
    summarySoldOut: "Все квартиры этажа проданы или в брони",
    floorLabel: "Этаж",
    floorOf: "{floor} из {total}",
    neighbour: "Этаж {floor}: свободно {available}",
    floorBelow: "Этаж ниже",
    floorAbove: "Этаж выше",
    planTitle: pluralForms(
      "План этажа {floor}, {count} квартира",
      "План этажа {floor}, {count} квартиры",
      "План этажа {floor}, {count} квартир",
    ),
    planLabel: "План этажа {floor}. Квартиры окрашены по статусу.",
    north: "С",
    southFacade: "Южный фасад, сторона парка",
    scale: "5 м",
    onThisFloor: "На этаже",
    residencesCount: pluralForms("{count} квартира", "{count} квартиры", "{count} квартир"),
    columns: { number: "№", bedrooms: "Спальни", area: "Площадь", price: "Цена", status: "Статус" },
    studio: "Студия",
    bedroomsShort: "{count} сп.",
    typeNames: ["Студия", "Одна спальня", "Две спальни", "Три спальни"],
    typeArea: "{type}, {area}",
    area: "{area} м²",
    // No-break space keeps "с террасой" together when the caption wraps in a grid cell.
    penthouse: "Пентхаус, с\u00a0террасой",
    residence: "Квартира {number}",
    clickToOpen: "Нажмите, чтобы открыть",
    notForSale: "Продана, недоступна",
    note: "Цены в {currency} по фиксированному курсу. Наличие обновляется вживую, как только квартиру бронируют.",
    openResidence: "Открыть квартиру {number}",
    availableOf: "Свободно {available} из {total}",
    unavailable: "Не удалось загрузить этаж. Обновите страницу через минуту или позвоните +1 (555) 010-2040.",
  },
  notFound: {
    metaTitle: "Страница не найдена · Aurora Residence",
    overline: "Ошибка 404",
    title: "Такой страницы нет",
    text: "Возможно, ссылка устарела или в ней опечатка. Квартиры и фасад в одном клике.",
    home: "На главную",
    residences: "Выбрать квартиру",
  },
};
