import type { residenceEn } from "./en-residence";

/** Russian texts of the residence page /residences/<number> and its enquiry form. */
export const residenceRu: typeof residenceEn = {
  residencePage: {
    metaTitle: "Квартира {number} · {type}, {area} · Aurora Residence",
    metaTitleShort: "Квартира {number} · Aurora Residence",
    metaDescription:
      "{type}, {area}: квартира {number} на {floor} этаже Aurora Residence, вид на {view}, {price}. План с площадями комнат, беспроцентная рассрочка и заявка напрямую менеджеру.",
    metaDescriptionSold:
      "{type}, {area}: квартира {number} на {floor} этаже Aurora Residence, вид на {view}. Квартира продана, посмотрите похожие, которые ещё свободны.",
    loading: "Загружаем квартиру",
    backToFloor: "Назад к этажу {floor}",
    backShort: "Этаж {floor}",
    breadcrumbs: "Навигационная цепочка",
    crumbResidences: "Квартиры",
    crumbFloor: "Этаж {floor}",
    crumbResidence: "Квартира {number}",
    updatedLive: "Обновляется вживую",
    title: "Квартира {number}",
    descriptions: [
      "Студия со светлой гостиной зоной, кухней вдоль стены и ванной у входа.",
      "Квартира с отдельной спальней и гостиной, объединённой с кухней.",
      "Квартира с двумя спальнями, мастер-ванной и гостиной с видом на парк.",
      "Угловая квартира с тремя спальнями, окнами на три стороны и большой гостиной.",
    ],
    floor: "Этаж",
    floorOf: "{floor} из {total}",
    bedrooms: "Спальни",
    area: "Площадь",
    view: "Вид",
    ceiling: "Высота потолков",
    ceilingValue: "{height} м",
    price: "Цена",
    pricePerMetre: "{perMetre} за м², или от {monthly} в месяц в рассрочку",
    request: "Оставить заявку",
    requestNote:
      "Менеджер позвонит в течение рабочего дня и, если решите, забронирует квартиру за вами на 7 дней.",
    reservedTitle: "В брони у другого покупателя",
    reservedNote:
      "Другой покупатель держит бронь до 7 дней. Заявку всё равно можно оставить: если бронь закончится без сделки, менеджер позвонит вам первым.",
    soldTitle: "Квартира продана",
    soldNote: "Она остаётся на сайте, чтобы вы могли сравнить планировки. Эти квартиры ещё свободны:",
    soldOnFloor: "Свободны на этаже {floor}",
    soldSimilar: "Та же планировка на других этажах",
    soldNone: "Свободных квартир с такой планировкой сейчас нет.",
    soldAll: "Все свободные квартиры",
    residenceShort: "Квартира {number}",
    unavailable:
      "Не удалось загрузить квартиру. Обновите страницу через минуту или позвоните +1 (555) 010-2040.",
    plan: {
      title: "План, {area}",
      label: "План квартиры {number} с площадями комнат",
      north: "С",
      entrance: "Вход",
      windows: "Окна на {side}, вид на {view}",
      ceiling: "Высота потолков {height} м",
      dimension: "{value} м",
      terrace: "Терраса {area} на кровле, на плане не показана",
      rooms: "Комнаты",
    },
    rooms: {
      studio: "Гостиная с кухней",
      living: "Гостиная с кухней",
      master: "Главная спальня",
      bedroom: "Спальня",
      ensuite: "Мастер-ванная",
      hall: "Холл",
      bath: "Санузел",
      entrance: "Прихожая",
      terrace: "Терраса",
    },
    position: {
      title: "На этаже {floor}",
      label: "Положение квартиры {number} на плане этажа {floor}",
      open: "Открыть план этажа {floor}",
      sides: { north: "северная сторона", south: "южная сторона, парк", east: "восточный торец", west: "западный торец" },
    },
    windowView: {
      overline: "Вид из окна",
      title: "Парк на {floors} ниже",
      floorWords: [
        "один этаж",
        "два этажа",
        "три этажа",
        "четыре этажа",
        "пять этажей",
        "шесть этажей",
        "семь этажей",
        "восемь этажей",
        "девять этажей",
        "десять этажей",
        "одиннадцать этажей",
      ],
      textExact: "Визуализация из гостиной квартиры {number}, {height} м над землёй.",
      textOther:
        "Визуализация из гостиной квартиры 7.03, 24 м над землёй. Квартира {number} находится на высоте {height} м и смотрит на тот же парк.",
      alt: "Закат над парком и городом из окна гостиной",
    },
    instalments: {
      overline: "Рассрочка",
      title: "Без процентов, напрямую от застройщика",
      text: "Часть цены вы платите сейчас, остальное равными ежемесячными платежами, без банка и без процентов.",
      downPayment: "Первый взнос",
      term: "Срок",
      months: "{count} мес.",
      monthly: "Платёж в месяц",
      monthlyNote: "{months} мес., без процентов",
      price: "Цена",
      downPaymentRow: "Первый взнос, {percent}%",
      instalmentsRow: "В рассрочку",
      disclaimer: "Предварительный расчёт в {currency}. Точный график фиксируется в договоре.",
    },
    similar: {
      overline: "Та же планировка, другие этажи",
      title: "Похожие квартиры",
      all: "Все квартиры",
      swipe: "Листайте, чтобы увидеть ещё",
      details: "Подробнее",
    },
  },
  residenceEnquiry: {
    overline: "Заявка",
    title: "Заявка на квартиру",
    lead: "Оставьте контакты, и менеджер перезвонит, чтобы договориться о показе.",
    yourResidence: "Ваша квартира",
    summary: "{bedrooms}  ·  {area}  ·  Этаж {floor} из {total}  ·  {price}",
    nameLabel: "Имя и фамилия",
    emailPlaceholder: "you@example.com",
    comment: "Комментарий, необязательно",
    commentPlaceholder: "Вопросы или удобное время для звонка",
    submit: "Отправить заявку",
    replyNote: "Менеджер ответит в течение рабочего дня.",
    close: "Закрыть заявку",
    errors: {
      comment: "Комментарий должен быть короче 2000 символов",
    },
  },
};
