import type { AdvantageItem, Dictionary, GalleryItem, PlaceItem, StatItem } from "./en";
import { enquiryRu } from "./ru-enquiry";
import { residenceRu } from "./ru-residence";
import { residencesRu } from "./ru-residences";

export const ru: Dictionary = {
  locale: {
    lang: "ru",
    intl: "ru-RU",
  },
  meta: {
    title: "Aurora Residence",
    description:
      "Шестьдесят шесть квартир на одиннадцати этажах над старым парком. Aurora Residence от Meridian Group.",
  },
  a11y: {
    skipToContent: "Перейти к содержанию",
    home: "Aurora Residence, на главную",
    mainNavigation: "Основное меню",
    footerNavigation: "Меню в подвале сайта",
    openMenu: "Открыть меню",
    closeMenu: "Закрыть меню",
    menu: "Меню",
    language: "Язык",
    currency: "Валюта",
    timeOfDay: "Время суток",
  },
  nav: {
    about: "О проекте",
    residences: "Квартиры",
    gallery: "Галерея",
    location: "Локация",
    progress: "Ход стройки",
    contacts: "Контакты",
  },
  settings: {
    language: "Язык",
    currency: "Валюта",
    languages: { en: "EN", ru: "RU" },
    currencies: { usd: "USD", eur: "EUR", kzt: "KZT" },
  },
  contacts: {
    phone: "+1 (555) 010-2040",
    email: "sales@aurora-residence.com",
    hours: "Пн-Сб, 10:00-19:00",
    salesOfficeHours: "Офис продаж, Пн-Сб, 10:00-19:00",
  },
  actions: {
    enquire: "Связаться",
  },
  hero: {
    overline: "Aurora Residence от Meridian Group",
    title: "Дом над парком",
    subtitle: "Шестьдесят шесть квартир на одиннадцати этажах и старый парк через дорогу.",
    cta: "Выбрать квартиру",
    scrollCue: "Листайте вниз",
    seeTheHouse: "Посмотреть дом",
    day: "День",
    evening: "Вечер",
    renderDayAlt: "Aurora Residence днём: одиннадцатиэтажный фасад из травертина с бронзовыми ламелями над парком",
    renderEveningAlt: "Aurora Residence в сумерках: светятся окна, тёплое вечернее небо",
  },
  stats: {
    label: "Aurora Residence в цифрах",
    items: [
      { value: 11, suffix: "", label: "Этажей" },
      { value: 66, suffix: "", label: "Квартир" },
      { value: 3, suffix: " мин", label: "До парка пешком" },
      { text: "4 кв. 2027", label: "Сдача дома" },
    ] as StatItem[],
  },
  about: {
    overline: "О проекте",
    title: "Спокойная архитектура и парк вместо сада",
    lead: "Aurora Residence - отдельный одиннадцатиэтажный дом от Meridian Group: шестьдесят шесть квартир, фасад в травертине с бронзовыми ламелями и озеленённый двор, который выходит прямо в парк.",
    text: "В каждой квартире окна в пол и глубокий балкон, поэтому свет и деревья становятся частью интерьера. От студий до квартир с тремя спальнями, на верхнем этаже пентхаусы.",
    facts: [
      { value: "3,2 м", label: "Высота потолков" },
      { value: "38-164 м²", label: "Площади квартир" },
      { value: "6", label: "Квартир на этаже" },
    ],
    cta: "Смотреть квартиры",
    imageAlt: "Гостиная квартиры с тремя спальнями, окна в пол с видом на парк",
    caption: "Гостиная, квартира с тремя спальнями. Архитектурная визуализация.",
  },
  advantages: {
    overline: "Почему Aurora",
    title: "Для неспешной городской жизни",
    lead: "Четыре вещи, в которых мы не шли на компромисс, от первого эскиза до последней дверной ручки.",
    items: [
      {
        id: "park",
        title: "Парк в трёх минутах",
        text: "Вековые липы и дубы, тихие аллеи и озеро в трёх минутах пешком от лобби.",
      },
      {
        id: "glass",
        title: "Окна в пол",
        text: "Потолки 3,2 метра и панорамное остекление: в комнатах светло с утра до вечера.",
      },
      {
        id: "courtyard",
        title: "Двор без машин",
        text: "Сад с водой и подсвеченными дорожками. Парковка спрятана под землю.",
      },
      {
        id: "concierge",
        title: "Консьерж 24/7",
        text: "Лобби с персоналом, личные кладовые и закрытый доступ на каждый этаж и в паркинг.",
      },
    ] as AdvantageItem[],
  },
  residencePicker: {
    overline: "Выбор квартиры",
    title: "Найдите свой этаж прямо на фасаде",
    lead: "Наведите курсор на дом, чтобы увидеть свободные квартиры на каждом этаже, и откройте план. Наличие обновляется вживую, как только квартиру бронируют.",
    leadTouch:
      "Нажмите на этаж, чтобы увидеть свободные квартиры, и откройте план. Наличие обновляется вживую, как только квартиру бронируют.",
    viewsLabel: "Способы выбора",
    views: { facade: "Фасад", grid: "Шахматка", list: "Список" },
    facadeAlt: "Aurora Residence в сумерках: одиннадцать этажей светящихся окон над садом во дворе",
    floorsLabel: "Этажи дома",
    floor: "Этаж {floor}",
    availableOf: "Свободно {available} из {total}",
    soldOut: "Всё продано",
    fromPrice: "от {price}",
    noData: "Наличие обновляется",
    noMatches: "Нет подходящих квартир",
    openPlan: "открыть план",
    hintPointer: "Нажмите на этаж, чтобы открыть план",
    hintTouch: "Нажмите на этаж, чтобы выбрать его",
    legendTitle: "Наличие вживую",
    cta: "Открыть интерактивный фасад",
    ctaFloor: "Открыть этаж {floor}",
  },
  gallery: {
    overline: "Галерея",
    title: "Свет в каждой комнате",
    lead: "Архитектурные визуализации квартир и вид с верхних этажей. Финальная отделка может отличаться.",
    items: [
      {
        id: "view",
        caption: "Закат над парком, вид с девятого этажа",
        alt: "Закат над парком и озером в панорамном окне девятого этажа",
      },
      {
        id: "bedroom",
        caption: "Главная спальня на рассвете",
        alt: "Главная спальня со стеной из травертина и окном в парк на рассвете",
      },
      {
        id: "living",
        caption: "Гостиная с угловым окном",
        alt: "Гостиная с угловым окном, низким диваном и обеденным столом у стекла",
      },
    ] as GalleryItem[],
    carouselLabel: "Изображения галереи",
    swipeHint: "Листайте, чтобы увидеть ещё",
    openImage: "Открыть изображение: {caption}",
    viewerLabel: "Просмотр изображений",
    close: "Закрыть",
    previous: "Предыдущее изображение",
    next: "Следующее изображение",
  },
  location: {
    overline: "Локация",
    title: "Всё в нескольких минутах пешком",
    lead: "Тихая жилая улица между парком и деловым кварталом. Школы, магазины и метро в нескольких минутах пешком.",
    places: [
      { id: "park", name: "Парк", mapName: "Парк", minutes: 3 },
      { id: "school", name: "Школа", mapName: "Школа", minutes: 6 },
      { id: "metro", name: "Станция метро", mapName: "Метро", minutes: 8 },
      { id: "mall", name: "Торговый центр", mapName: "ТЦ", minutes: 12 },
      { id: "business", name: "Деловой центр", mapName: "Деловой центр", minutes: 15 },
    ] as PlaceItem[],
    walk: "{minutes} мин пешком",
    mapMinutes: "{minutes} мин",
    mapLabel: "Карта района со временем в пути пешком от Aurora Residence",
    home: "Aurora Residence",
    entrance: "Главный вход",
    north: "С",
    scale: "200 м",
    dragHint: "Перетащите, чтобы сдвинуть карту",
  },
  progress: {
    overline: "Ход строительства",
    title: "По графику: сдача в 4 кв. 2027",
    lead: "Обновляем каждый месяц, с фотографиями со стройки. Последнее обновление: октябрь 2026.",
    currentStage: 2,
    currentPercent: 60,
    stages: [
      {
        number: "01",
        period: "2 кв. 2025",
        title: "Фундамент",
        text: "Сваи, фундаментная плита и два уровня подземного паркинга.",
      },
      {
        number: "02",
        period: "2 кв. 2026",
        title: "Каркас",
        text: "Возведены одиннадцать этажей и кровля. Каркас завершён.",
      },
      {
        number: "03",
        period: "4 кв. 2026 - 2 кв. 2027",
        title: "Фасад и инженерия",
        text: "Облицовка травертином, бронзовые ламели, остекление, лифты и инженерные системы.",
      },
      {
        number: "04",
        period: "4 кв. 2027",
        title: "Отделка и ключи",
        text: "Общественные зоны, благоустройство двора, приёмка дома и передача ключей.",
      },
    ],
    stageMeta: "Этап {number}  ·  {period}",
    completed: "Завершён",
    inProgress: "В работе, {percent}%",
    planned: "Впереди",
  },
  footer: {
    tagline: "Одиннадцать этажей спокойной архитектуры над парком. Проект Meridian Group.",
    residencesTitle: "Квартиры",
    chooseOnFacade: "Выбор на фасаде",
    floorGrid: "Шахматка",
    allResidences: "Все квартиры",
    projectTitle: "Проект",
    salesOfficeTitle: "Офис продаж",
    copyright: "© 2026 Meridian Group. Вымышленный проект для портфолио.",
    privacy: "Политика конфиденциальности",
  },
  status: {
    available: "Свободна",
    reserved: "Бронь",
    sold: "Продана",
  },
  ...residencesRu,
  ...residenceRu,
  ...enquiryRu,
};
