/**
 * Every `code` the API can return in an error body. The web app imports this
 * file by a relative path, so it must stay plain TypeScript without imports.
 */
export const ERROR_CODES = {
  // Fallbacks by HTTP status for errors without a specific code.
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  VALIDATION_FAILED: 'VALIDATION_FAILED',
  NOTHING_TO_UPDATE: 'NOTHING_TO_UPDATE',

  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  LOGIN_LOCKED: 'LOGIN_LOCKED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',

  RESIDENCE_NOT_FOUND: 'RESIDENCE_NOT_FOUND',
  ENQUIRY_NOT_FOUND: 'ENQUIRY_NOT_FOUND',

  RESIDENCE_SOLD: 'RESIDENCE_SOLD',
  RESIDENCE_RESERVED: 'RESIDENCE_RESERVED',
  NO_ACTIVE_RESERVATION: 'NO_ACTIVE_RESERVATION',
  ENQUIRY_HAS_NO_RESIDENCE: 'ENQUIRY_HAS_NO_RESIDENCE',
  ENQUIRY_RESIDENCE_MISMATCH: 'ENQUIRY_RESIDENCE_MISMATCH',
  ENQUIRY_CLOSED: 'ENQUIRY_CLOSED',
  ENQUIRY_RESIDENCE_EXISTS: 'ENQUIRY_RESIDENCE_EXISTS',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const ALL_ERROR_CODES = Object.values(ERROR_CODES) as ErrorCode[];
